### PR TITLE
add recent hypr-utilities

### PR DESCRIPTION
**Pull request by BackHDLP**
we should check the hyprwm org more often with the speed Vaxry creates new things lol

### CODE REVIEW

**Comment by yavko** [comment]
I already added them, but they probably should be there too https://github.com/hyprland-community/awesome-hyprland/commit/4cc099568b6bb44d67d0218669e6fcbfca2e937f

**Comment by BackHDLP** [comment]
oh oop didn't notice.
I do believe they belong in the `Official tools` section, given that hyprpaper and hyprpicker aren't in their appropriate sections.

**Comment by yavko** [comment]
> oh oop didn't notice. I do believe they belong in the `Official tools` section, given that hyprpaper and hyprpicker aren't in their appropriate sections.

dy think it'd be better to remove them from the sections there?

**Comment by BackHDLP** [comment]
> dy think it'd be better to remove them from the sections there?

that or add hyprpaper and hyprpicker to fitting categories too

**Comment by yavko** [comment]
> > dy think it'd be better to remove them from the sections there?
> 
> that or add hyprpaper and hyprpicker to fitting categories too

yeah, then could you add those to their own categories too?

**Comment by BackHDLP** [comment]
hope that works

**Review by yavko — APPROVED** [review]

**Comment by yavko** [comment]
sick

**Pull request merged**
